name: Upload to Debian repo

on:
  release:
    types: [published]

jobs:
  repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
      - name: Install APT dependencies
        run: sudo apt install build-essential devscripts debhelper equivs rubygems
        working-directory: repo
      - name: Install PackageCloud CLI
        run: sudo gem install package_cloud
      - name: Build Debian package
        run: sudo mk-build-deps -ir && debuild -uc -us
        working-directory: repo
      - name: Push package
        run: package_cloud push srobo/kit/debian/bullseye *.deb
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}